# metamodel_version: 1.11.0id: AdditionalFixedPayments
schema_generating: true
description: A class to specify the events that will give rise to the payment additional
  fixed payments.
display_name: AdditionalFixedPayments
document_category: AdditionalFixedPayments
weight: 20
fields:
- id: interestShortfallReimbursement
  description: 'An additional Fixed Payment Event. Corresponds to the payment by or
    on behalf of the Issuer of an actual interest amount in respect to the reference
    obligation that is greater than the expected interest amount. ISDA 2003 Term:
    Interest Shortfall Reimbursement.'
  display_name: interestShortfallReimbursement
- id: principalShortfallReimbursement
  description: 'An additional Fixed Payment Event. Corresponds to the payment by or
    on behalf of the Issuer of an actual principal amount in respect to the reference
    obligation that is greater than the expected principal amount. ISDA 2003 Term:
    Principal Shortfall Reimbursement.'
  display_name: principalShortfallReimbursement
- id: writedownReimbursement
  description: 'An Additional Fixed Payment. Corresponds to the payment by or on behalf
    of the issuer of an amount in respect to the reference obligation in reduction
    of the prior writedowns. ISDA 2003 Term: Writedown Reimbursement.'
  display_name: writedownReimbursement
