# metamodel_version: 1.11.0id: AdjustableDate
schema_generating: true
description: A class for defining a date that shall be subject to adjustment if it
  would otherwise fall on a day that is not a business day in the specified business
  centers, together with the convention for adjusting the date.
display_name: AdjustableDate
document_category: AdjustableDate
weight: 20
fields:
- id: unadjustedDate
  description: A date subject to adjustment. While in FpML this date is required,
    this cardinality constraint has been relaxed as part of the CDM in order to support
    the FRA representation, which effective and termination dates are specified in
    FpML as adjusted dates.
  display_name: unadjustedDate
- id: dateAdjustments
  description: The business day convention and financial business centers used for
    adjusting the date if it would otherwise fall on a day that is not a business
    date in the specified business centers.
  display_name: dateAdjustments
- id: dateAdjustmentsReference
  description: A pointer style reference to date adjustments defined elsewhere in
    the document.
  display_name: dateAdjustmentsReference
- id: adjustedDate
  description: The date once the adjustment has been performed. (Note that this date
    may change if the business center holidays change).
  display_name: adjustedDate
