# metamodel_version: 1.11.0id: AgencyRatingCriteria
schema_generating: true
description: Represents a class to specify a credit notation.
display_name: AgencyRatingCriteria
document_category: AgencyRatingCriteria
weight: 20
fields:
- id: creditNotation
  description: Indicates the agency rating criteria specified for the asset or issuer.
  display_name: AgencyRatingCriteria_creditNotation
- id: mismatchResolution
  description: Indicator for options to be used if several agency ratings (>1) are
    specified and its necessary to identify specific charateristics. i.e (lowest or
    highest).
  display_name: AgencyRatingCriteria_mismatchResolution
- id: referenceAgency
  description: identifies the dominant reference agency if there is a missmatch and
    several reference agencies exsist.
  display_name: AgencyRatingCriteria_referenceAgency
- id: boundary
  description: Indicates the boundary of a credit agency rating i.e minimum or maximum.
  display_name: boundary
