# metamodel_version: 1.11.0id: Agreement
schema_generating: true
description: Specification of the standard set of terms that define a legal agreement.
display_name: Agreement
document_category: Agreement
weight: 20
fields:
- id: creditSupportAgreementElections
  description: Elections to specify a Credit Support Annex or Credit Support Deed
    for Intial or Variation Margin.
  display_name: creditSupportAgreementElections
- id: collateralTransferAgreementElections
  description: Elections to specify a Collateral Transfer Agreement.
  display_name: collateralTransferAgreementElections
- id: securityAgreementElections
  description: Elections to specify a Security agreement.
  display_name: securityAgreementElections
- id: masterAgreementSchedule
  description: Elections to specify a Master Agreement Schedule.
  display_name: masterAgreementSchedule
- id: transactionAdditionalTerms
  description: Any additional terms which mainly intend to specify the extraordinary
    events that may affect a trade and the related contractual rights and obligation
    of the parties when this happens
  display_name: transactionAdditionalTerms
- id: masterAgreementElections
  description: A legal representation of the different possible master agreements
  display_name: masterAgreementElections
