# metamodel_version: 1.11.0id: AssetDeliveryProfileBlock
schema_generating: true
description: Defines a delivery profile block, including start and end time, days
  of the week, duration, delivery capacity and price time interval quantity.
display_name: AssetDeliveryProfileBlock
document_category: AssetDeliveryProfileBlock
weight: 20
fields:
- id: startTime
  description: The start time of the delivery interval for each block or shape.
  display_name: startTime
- id: endTime
  description: The end time of the delivery interval for each block or shape.
  display_name: endTime
- id: dayOfWeek
  description: The days of the week of the delivery.
  display_name: AssetDeliveryProfileBlock_dayOfWeek
  cardinality: multi
- id: deliveryCapacity
  description: The number of units included in the transaction for each delivery interval
  display_name: deliveryCapacity
- id: priceTimeIntervalQuantity
  description: Price per quantity per delivery time interval.
  display_name: priceTimeIntervalQuantity
