# metamodel_version: 1.11.0id: AssetPayout
schema_generating: true
description: Security finance payout specification in case the product payout involves
  some form of security collateral, as in a securities financing transaction. Plus
  additional description for ICMA.
display_name: AssetPayout
document_category: AssetPayout
weight: 20
fields:
- id: payerReceiver
  description: Canonical representation of the payer and receiver parties applicable
    to each payout leg.
  display_name: PayoutBase_payerReceiver
- id: priceQuantity
  description: Each payout leg must implement the quantity concept as a 'resolvable'
    type, which allows for different payout legs to be linked to each other (e.g.
    in the case of cross-curreny products).
  display_name: PayoutBase_priceQuantity
  cardinality: multi
- id: principalPayment
  description: The specification of the principal exchange. Optional as only applicable
    in the case of cross-currency or zero-coupon swaps with a final payment.
  display_name: principalPayment
- id: settlementTerms
  description: Each payout leg must specifies its settlement terms, including the
    delivery type (i.e. cash vs physical, and their respective terms), the transfer
    type (DvP etc.) and settlement date, if any.
  display_name: PayoutBase_settlementTerms
- id: assetLeg
  description: Defines each asset movement as a buy/sell at different dates, typically
    1 near leg and 1 far leg in a securities financing transaction.
  display_name: assetLeg
  cardinality: multi
- id: underlier
  description: Specifies the Purchased Asset, usually a Security.
  display_name: AssetPayout_underlier
- id: minimumFee
  description: A contractual minimum amount which the borrower will pay, regardless
    of the duration of the loan. A mechanism for making sure that a trade generates
    enough income.
  display_name: AssetPayout_minimumFee
- id: dividendTerms
  description: Specifies the terms under which dividends received by the borrower
    are passed through to the lender.
  display_name: AssetPayout_dividendTerms
- id: tradeType
  description: The trade type, eg repurchase transaction or buy/sell-back.
  display_name: tradeType
