# metamodel_version: 1.11.0id: CalculationAndTimingVariationMargin
schema_generating: true
description: Specification of the Calculation, Valuation and Timing terms specific
  to the Variation Margin Credit Support Annex.
display_name: CalculationAndTimingVariationMargin
document_category: CalculationAndTimingVariationMargin
weight: 20
fields:
- id: notificationTime
  description: The time by which a demand for the Transfer of Eligible Credit Support
    (IM) or Posted Credit Support (IM) needs to be made in order for the transfer
    to take place in accordance with the Transfer Timing provisions.
  display_name: notificationTime
- id: valuationDate
  description: Details of the days on which calculations are to be made to determine
    the Delivery Amount and/or Return Amount.
  display_name: valuationDate
- id: valuationTime
  description: Specifies the time on which the value of collateral or exposure are
    calculated in accordance with the agreement.
  display_name: valuationTime
- id: valuationAgent
  description: Details of the party valuating the collateral to be delivered or returned.
  display_name: CalculationAndTimingVariationMargin_valuationAgent
- id: valuationDateLocation
  description: The specified location where the credit exposure will be calculated
    by the respective parties.
  display_name: valuationDateLocation
