# metamodel_version: 1.11.0id: CalculationCurrencyElection
schema_generating: true
description: A class to specify the ISDA SIMM Calculation Currency.
display_name: CalculationCurrencyElection
document_category: CalculationCurrencyElection
weight: 20
fields:
- id: party
  description: The party which the SIMM Calculation Currency qualification applies
    to.
  display_name: CalculationCurrencyElection_party
- id: isBaseCurrency
  description: The SIMM Calculation Currency (also known as SIMM Reporting Currency)
    means the Base Currency when True. It means a different currency when False. In
    that latter case, the SIMM Calculation Currency is specified as part of the currency
    attribute.
  display_name: isBaseCurrency
- id: currency
  description: The currency in which the ISDA SIMM Calculation is denominated, when
    different from the Base Currency. The list of valid currencies is not presently
    positioned as an enumeration as part of the CDM because that scope is limited
    to the values specified by ISDA and FpML. As a result, implementers have to make
    reference to the relevant standard, such as the ISO 4217 standard for currency
    codes.
  display_name: CalculationCurrencyElection_currency
