# metamodel_version: 1.11.0id: Cash
schema_generating: true
description: An Asset that consists solely of a monetary holding in a currency. The
  currency of the Cash asset is held in the string Identifier (from AssetBase) and
  the AssetIdTypeEnum must be set to define that a CurrencyCode is set.  The function
  SetCashCurrency can be used to create (or update) a Cash object and the function
  GetCashCurrency can be used to retrieve the currency of a Cash object.
display_name: Cash
document_category: Cash
weight: 20
fields:
- id: identifier
  description: Asset Identifiers are used to uniquely identify an Asset, using a specified
    Asset Identifier Type.
  display_name: identifier
  cardinality: multi
- id: taxonomy
  description: Defines the taxonomy of an object by combining a taxonomy source (i.e.
    the rules to classify the object) and a value (i.e. the output of those rules
    on the object.
  display_name: taxonomy
  cardinality: multi
- id: isExchangeListed
  description: Defines whether the Asset is listed on a public exchange.
  display_name: isExchangeListed
- id: exchange
  description: If the Asset is listed, defines the public exchange of the listing.
  display_name: exchange
- id: relatedExchange
  description: Provides the related Exchanges, if applicable.
  display_name: relatedExchange
  cardinality: multi
- id: assetType
  description: Specifies the type of asset.
  display_name: assetType
