# metamodel_version: 1.11.0id: ConcentrationLimitCriteria
schema_generating: true
description: Respresents a class to describe a set of criteria to describe specific
  assets that the concentration limits apply to.
display_name: ConcentrationLimitCriteria
document_category: ConcentrationLimitCriteria
weight: 20
fields:
- id: collateralCriteria
  description: The specific criteria that applies. It can be created using AND, OR
    and NOT logic, and both asset and issuer characteristics.
  display_name: collateralCriteria
- id: appliesTo
  description: Specifies which of the two counterparties the criteria applies to (either
    one or both counterparties). This attribute is optional, in case the applicable
    party is already specified elsewhere within a party election.
  display_name: appliesTo
  cardinality: multi
- id: restrictTo
  description: Restrict the criteria to only apply to a specific type of margin, ie
    IM or VM.
  display_name: restrictTo
- id: ratingPriorityResolution
  description: Denotes which Criteria has priority if more than one agency rating
    applies.
  display_name: ratingPriorityResolution
- id: concentrationLimitType
  description: Specifies the type of concentration limit to be applied.
  display_name: concentrationLimitType
- id: averageTradingVolume
  description: Specifies an average trading volume on an exchange in relation to Equity
    products.
  display_name: averageTradingVolume
