# metamodel_version: 1.11.0id: ContactInformationElection
schema_generating: true
description: Specifies the party reference and the associated contact information.
display_name: ContactInformationElection
document_category: ContactInformationElection
weight: 20
fields:
- id: partyReference
  description: The party to which the election and details apply.
  display_name: ContactInformationElection_partyReference
- id: primaryContactInformation
  description: The main notice/address information of the party.
  display_name: primaryContactInformation
