# metamodel_version: 1.11.0id: CounterpartyPosition
schema_generating: true
description: A Position describes the accumulated effect of a set of securities or
  financial transactions.
display_name: CounterpartyPosition
document_category: CounterpartyPosition
weight: 20
fields:
- id: contractDetails
  description: Represents information specific to trades or positions involving contractual
    products.
  display_name: ContractBase_contractDetails
- id: executionDetails
  description: Defines specific attributes that relate to trade or position executions.
  display_name: ContractBase_executionDetails
- id: collateral
  description: Represents the collateral obligations of a party.
  display_name: ContractBase_collateral
- id: positionIdentifier
  description: Represents the identifier(s) that uniquely identify a position for
    an identity issuer. A position can include multiple identifiers, for example an
    internal position identifer and a UTI (Unique Trade Identifier).
  display_name: positionIdentifier
  cardinality: multi
- id: openDateTime
  description: The date and time when the position was opened.
  display_name: openDateTime
- id: tradeReference
  description: Reference to all the trades that constitute the position.
  display_name: CounterpartyPosition_tradeReference
  cardinality: multi
- id: party
  description: The parties involved in the position, including the Clearing Organization.
  display_name: CounterpartyPosition_party
  cardinality: multi
- id: partyRole
  description: Represents the role each specified party takes in the position.
  display_name: CounterpartyPosition_partyRole
  cardinality: multi
- id: positionBase
  description: Encapsulates the core constituents that characterize a position.
  display_name: positionBase
