# metamodel_version: 1.11.0id: CreditEvent
schema_generating: true
description: Specifies the relevant data regarding a credit event.
display_name: CreditEvent
document_category: CreditEvent
weight: 20
fields:
- id: creditEventType
  description: The type of credit event taking place.
  display_name: creditEventType
- id: eventDeterminationDate
  description: The date in which the credit event is determined by the Credit Derivatives
    Determinations Comitee.
  display_name: eventDeterminationDate
- id: auctionDate
  description: The date on which the auction is scheduled to occur.
  display_name: auctionDate
- id: finalPrice
  description: The final price resulting from the auction.
  display_name: finalPrice
- id: recoveryPercent
  description: The percentage of the original value of the asset affected by the credit
    event that can be recovered.
  display_name: recoveryPercent
- id: publiclyAvailableInformation
  description: A public information source, e.g. a particular newspaper or electronic
    news service, that may publish relevant information used in the determination
    of whether or not a credit event has occurred.
  display_name: publiclyAvailableInformation
  cardinality: multi
- id: referenceInformation
  description: The reference entity, part of a credit basket, impacted by the credit
    event.
  display_name: referenceInformation
