# metamodel_version: 1.11.0id: CreditDefaultPayout
schema_generating: true
description: ' The credit default payout specification provides the details necessary
  for determining when a credit payout will be triggered as well as the parameters
  for calculating the payout and the settlement terms. The associated globalKey denotes
  the ability to associate a hash value to the CreditDefaultPayout instantiations
  for the purpose of model cross-referencing, in support of functionality such as
  the event effect and the lineage.'
display_name: CreditDefaultPayout
document_category: CreditDefaultPayout
weight: 20
fields:
- id: payerReceiver
  description: Canonical representation of the payer and receiver parties applicable
    to each payout leg.
  display_name: PayoutBase_payerReceiver
- id: priceQuantity
  description: Each payout leg must implement the quantity concept as a 'resolvable'
    type, which allows for different payout legs to be linked to each other (e.g.
    in the case of cross-curreny products).
  display_name: PayoutBase_priceQuantity
  cardinality: multi
- id: principalPayment
  description: The specification of the principal exchange. Optional as only applicable
    in the case of cross-currency or zero-coupon swaps with a final payment.
  display_name: principalPayment
- id: settlementTerms
  description: Each payout leg must specifies its settlement terms, including the
    delivery type (i.e. cash vs physical, and their respective terms), the transfer
    type (DvP etc.) and settlement date, if any.
  display_name: PayoutBase_settlementTerms
- id: generalTerms
  description: The specification of the non-monetary terms for the Credit Derivative
    Transaction, including the buyer and seller and selected items from the ISDA 2014
    Credit Definition article II, such as the reference obligation and related terms.
  display_name: generalTerms
- id: protectionTerms
  description: Specifies the terms for calculating a payout to protect the buyer of
    the swap in the case of a qualified credit event. These terms include the applicable
    credit events, the reference obligation, and in the case of a CDS on mortgage-backed
    securities, the floatingAmountEvents.
  display_name: protectionTerms
  cardinality: multi
- id: transactedPrice
  description: The qualification of the price at which the contract has been transacted,
    in terms of market fixed rate, initial points, market price and/or quotation style.
    In FpML, those attributes are positioned as part of the fee leg.
  display_name: transactedPrice
