# metamodel_version: 1.11.0id: CreditRatingDebt
schema_generating: true
description: Specifies the credit rating debt type(s) associated with the credit rating
  notation and scale. When several debt types are specified, they must be qualified
  through an 'any' or 'all'.
display_name: CreditRatingDebt
document_category: CreditRatingDebt
weight: 20
fields:
- id: debtType
  description: Specifies when there is only one debt type. FpML doesn't specify values
    in relation to the associated scheme, which is hence not specified as an enumeration
    as part of the CDM.
  display_name: CreditRatingDebt_debtType
- id: debtTypes
  description: Specifies if there are several debt types, alongside an 'any' or 'all'
    or all condition. As an example, Baa1 rating is required for any long term debt
    and deposit.
  display_name: debtTypes
