# metamodel_version: 1.11.0id: DividendTerms
schema_generating: true
description: Information related to dividends and payments.
display_name: DividendTerms
document_category: DividendTerms
weight: 20
fields:
- id: manufacturedIncomeRequirement
  description: Specifies the proportion of the value of the dividend on the borrowed
    shares that the borrower is legally obligated to return to the lender.
  display_name: manufacturedIncomeRequirement
- id: dividendEntitlement
  description: Defines the date on which the receiver of the equity return is entitled
    to the dividend.
  display_name: dividendEntitlement
- id: minimumBillingAmount
  description: daily fee increments accrue until a threshold is crossed, at which
    point payment becomes due)
  display_name: minimumBillingAmount
