# metamodel_version: 1.11.0id: ExerciseFeeSchedule
schema_generating: true
description: A class to define a fee or schedule of fees to be payable on the exercise
  of an option. This fee may be defined as an amount or a percentage of the notional
  exercised. As a difference with FpML, it extends the BuyerSeller class.
display_name: ExerciseFeeSchedule
document_category: ExerciseFeeSchedule
weight: 20
fields:
- id: payer
  description: Specifies the counterparty responsible for making the payments defined
    by this structure.  The party is one of the two principal parties to the transaction.
  display_name: payer
- id: receiver
  description: Specifies the party that receives the payments corresponding to this
    structure.  The party is one of the two counterparties to the transaction.
  display_name: receiver
- id: notionalReference
  description: A pointer style reference to the associated notional schedule defined
    elsewhere in the document.
  display_name: notionalReference
- id: feeAmountSchedule
  description: The exercise fee amount schedule. The fees are expressed as currency
    amounts. The currency of the fee is assumed to be that of the notional schedule
    referenced.
  display_name: feeAmountSchedule
- id: feeRateSchedule
  description: The exercise free rate schedule. The fees are expressed as percentage
    rates of the notional being exercised. The currency of the fee is assumed to be
    that of the notional schedule referenced.
  display_name: feeRateSchedule
- id: feePaymentDate
  description: The date on which exercise fee(s) will be paid. It is specified as
    a relative date.
  display_name: feePaymentDate
