# metamodel_version: 1.11.0id: HoldingAndUsingPostedCollateralElection
schema_generating: true
description: Specifies the parties' elections related to the holding and using of
  posted collateral.
display_name: HoldingAndUsingPostedCollateralElection
document_category: HoldingAndUsingPostedCollateralElection
weight: 20
fields:
- id: party
  description: The party to which the elections apply.
  display_name: HoldingAndUsingPostedCollateralElection_party
- id: eligibilityToHoldCollateral
  description: The specification of the conditions under which a party and its custodian(s)
    are entitled to hold posted collateral.
  display_name: eligibilityToHoldCollateral
- id: useOfPostedCollateral
  description: Indicates whether the party has the right to reuse, rehypothecate,
    or otherwise make use of the posted collateral. 'True' if the party has the right,'False'
    if the party does not have the right.
  display_name: useOfPostedCollateral
