# metamodel_version: 1.11.0id: LimitApplicable
schema_generating: true
display_name: LimitApplicable
document_category: LimitApplicable
weight: 20
fields:
- id: limitType
  description: Standard code to indicate which type of credit line is being referred
    to - i.e. IM, DV01, PV01, CS01, Notional, Clip Size, Notional, maximumOrderQuantity.
  display_name: limitType
- id: clipSize
  description: This element is required in FpML, optional in CDM for the purpose of
    accommodating the CME data representation while making reference to the FpML one.
  display_name: clipSize
- id: amountUtilized
  description: The limit utilised by all the cleared trades for the limit level and
    limit type. While the attribute is of type integer in FpML and the CME schema,
    it has been specified to be of type number in the CDM to take into consideration
    java size limits as well as for consistency purposes with the way most monetary
    amounts are expressed.
  display_name: amountUtilized
- id: utilization
  display_name: utilization
- id: amountRemaining
  description: The limit remaining for the limit level and limit type. This does not
    take into account any pending trades. While the attribute is of type integer in
    FpML and the CME schema, it has been specified to be of type number in the CDM
    to take into consideration java size limits as well as for consistency purposes
    with the way most monetary amounts are expressed.
  display_name: amountRemaining
- id: currency
  description: The currency in which the applicable limit is denominated. The list
    of valid currencies is not presently positioned as an enumeration as part of the
    CDM because that scope is limited to the values specified by ISDA and FpML. As
    a result, implementers have to make reference to the relevant standard, such as
    the ISO 4217 standard for currency codes.
  display_name: LimitApplicable_currency
- id: velocity
  display_name: velocity
