# metamodel_version: 1.11.0id: MasterAgreementDatedAsOfDate
schema_generating: true
description: Defines the dates agreed by the parties as the date of the Credit Support
  Annex or Credit Support Deed.
display_name: MasterAgreementDatedAsOfDate
document_category: MasterAgreementDatedAsOfDate
weight: 20
fields:
- id: masterAgreementDatedAsOfDate
  description: The date agreed by the parties as the Dated as of Date for the Master
    Agreement.
  display_name: MasterAgreementDatedAsOfDate_masterAgreementDatedAsOfDate
- id: additionalLanguage
  description: The additional language that might be specified by the parties to the
    legal agreement.
  display_name: MasterAgreementDatedAsOfDate_additionalLanguage
