# metamodel_version: 1.11.0id: MasterAgreementVariableSet
schema_generating: true
description: Defines a type where additional variables associated to clauses and their
  variants can be described.
display_name: MasterAgreementVariableSet
document_category: MasterAgreementVariableSet
weight: 20
fields:
- id: variableSet
  description: For some variants a table of variables is required. To support this
    use case we need to be able to specify variables within variables. Including a
    variable set here gives us infinite nesting opportunities - realistically we are
    only ever expecting that a table would need to be defined for any particular clause,
    so we would expect two levels of nesting as a maximum i.e. variableSet->variableSet->name/value.
  display_name: MasterAgreementVariableSet_variableSet
  cardinality: multi
- id: name
  description: The name of the variable.
  display_name: MasterAgreementVariableSet_name
- id: value
  description: The value for this variable.
  display_name: MasterAgreementVariableSet_value
