# metamodel_version: 1.11.0id: MeasureSchedule
schema_generating: true
description: A set of measures, all in the same unit, where the values are defined
  through a schedule of steps. The initial value may be defined either as part of
  the steps, or using the single amount attribute.
display_name: MeasureSchedule
document_category: MeasureSchedule
weight: 20
fields:
- id: value
  description: Specifies the value of the measure as a number. Optional because in
    a measure vector or schedule, this single value may be omitted.
  display_name: value
- id: unit
  description: Qualifies the unit by which the amount is measured. Optional because
    a measure may be unit-less (e.g. when representing a ratio between amounts in
    the same unit).
  display_name: unit
- id: datedValue
  description: A schedule of step date and value pairs. On each step date the associated
    step value becomes effective. The step dates are used to order the steps by ascending
    order. This attribute is optional so the data type may be used to define a schedule
    with a single value.
  display_name: datedValue
  cardinality: multi
