# metamodel_version: 1.11.0id: Money
schema_generating: true
description: Defines a monetary amount in a specified currency.
display_name: Money
document_category: Money
weight: 20
fields:
- id: value
  description: Specifies the value of the measure as a number. Optional because in
    a measure vector or schedule, this single value may be omitted.
  display_name: value
- id: unit
  description: Qualifies the unit by which the amount is measured. Optional because
    a measure may be unit-less (e.g. when representing a ratio between amounts in
    the same unit).
  display_name: unit
- id: datedValue
  description: A schedule of step date and value pairs. On each step date the associated
    step value becomes effective. The step dates are used to order the steps by ascending
    order. This attribute is optional so the data type may be used to define a schedule
    with a single value.
  display_name: datedValue
  cardinality: multi
- id: multiplier
  description: Defines an optional number that the quantity should be multiplied by
    to derive a total quantity. This number is associated to a unit. For example in
    the case of the Coal (API2) CIF ARA (ARGUS-McCloskey) Futures Contract on the
    CME, where the unit would be contracts, the multiplier value would 1,000 and the
    mulitiplier unit would be 1,000 MT (Metric Tons).
  display_name: multiplier
- id: frequency
  description: Defines the frequency to be used when defining a quantity. For example
    a quantity may be specified as a number of barrels of oil per day, which needs
    multiplying by the number of days in the relevant period to get the total quantity
    as a number of barrels.
  display_name: frequency
