# metamodel_version: 1.11.0id: NonNegativeStep
schema_generating: true
description: A class defining a step date and non-negative step value pair. This step
  definitions are used to define varying rate or amount schedules, e.g. a notional
  amortisation or a step-up coupon schedule.
display_name: NonNegativeStep
document_category: NonNegativeStep
weight: 20
fields:
- id: stepDate
  description: The date on which the associated stepValue becomes effective. This
    day may be subject to adjustment in accordance with a business day convention.
  display_name: stepDate
- id: stepValue
  description: The non-negative rate or amount which becomes effective on the associated
    stepDate. A rate of 5% would be represented as 0.05.
  display_name: stepValue
