# metamodel_version: 1.11.0id: NoticeInformationElection
schema_generating: true
description: Specifies the party reference and the associated notice and contact information.
display_name: NoticeInformationElection
document_category: NoticeInformationElection
weight: 20
fields:
- id: partyReference
  description: The party to which the election and details apply.
  display_name: ContactInformationElection_partyReference
- id: primaryContactInformation
  description: The main notice/address information of the party.
  display_name: primaryContactInformation
- id: additionalContactInformation
  description: Additional notice/address information of the party.
  display_name: additionalContactInformation
  cardinality: multi
