# metamodel_version: 1.11.0id: ObservationShiftCalculation
schema_generating: true
description: Parameters to describe the observation shift for a daily compounded or
  averaged floating rate. This type is used to represent modular computed rates in
  interestRatePayouts.
display_name: ObservationShiftCalculation
document_category: ObservationShiftCalculation
weight: 20
fields:
- id: offsetDays
  description: The number of days of observation shift.
  display_name: ObservationShiftCalculation_offsetDays
- id: calculationBase
  description: Whether the rate is calculated in advance, in arrears, or relative
    to a reset date.
  display_name: calculationBase
- id: additionalBusinessDays
  description: Any additional business days that be applicable.
  display_name: additionalBusinessDays
