# metamodel_version: 1.11.0id: OtherEligibleAndPostedSupport
schema_generating: true
description: Specifies the Other Eligible Support elections.
display_name: OtherEligibleAndPostedSupport
document_category: OtherEligibleAndPostedSupport
weight: 20
fields:
- id: applicableValue
  description: The definition of 'Value' with respect to Other Eligible Support and
    Other Posted Support.
  display_name: applicableValue
- id: applicableTransfer
  description: The definition of 'Transfer' with respect to Other Eligible Support
    and Other Posted Support.
  display_name: applicableTransfer
- id: value
  description: Details how particular types of collateral are valued (other than in
    respect of a default).
  display_name: OtherEligibleAndPostedSupport_value
