# metamodel_version: 1.11.0id: ParametricDates
schema_generating: true
description: Defines rules for the dates on which the price will be determined.
display_name: ParametricDates
document_category: ParametricDates
weight: 20
fields:
- id: dayType
  description: Denotes the enumerated values to specify the day type classification
    used in counting the number of days between two dates.
  display_name: ParametricDates_dayType
- id: dayDistribution
  description: Denotes the method by which the pricing days are distributed across
    the pricing period.
  display_name: dayDistribution
- id: dayOfWeek
  description: Indicates the days of the week on which the price will be determined.
  display_name: ParametricDates_dayOfWeek
  cardinality: multi
- id: dayFrequency
  description: Defines the occurrence of the dayOfWeek within the pricing period on
    which pricing will take place, e.g. the 3rd Friday within each Calculation Period.
    If omitted, every dayOfWeek will be a pricing day.
  display_name: dayFrequency
- id: lag
  description: The pricing period per calculation period if the pricing days do not
    wholly fall within the respective calculation period.
  display_name: lag
- id: businessCenters
  description: The enumerated values to specify the business centers.
  display_name: ParametricDates_businessCenters
