# metamodel_version: 1.11.0id: PartyIdentifier
schema_generating: true
description: Comprises an identifier and a source. The associated metadata key denotes
  the ability to associate a hash value to the PartyIdentifier instantiations for
  the purpose of model cross-referencing, in support of functionality such as the
  event effect and the lineage.
display_name: PartyIdentifier
document_category: PartyIdentifier
weight: 20
fields:
- id: identifier
  description: Provides an identifier associated with a party. The identifier is unique
    within the public source specified in the source attribute.
  display_name: PartyIdentifier_identifier
  cardinality: multi
- id: identifierType
  description: Defines the source of the identifier.
  display_name: PartyIdentifier_identifierType
