# metamodel_version: 1.11.0id: PartyChangeInstruction
schema_generating: true
description: 'Specifies instruction to change the party on a trade. This primitive
  instruction is used in a number of scenarios including: clearing, allocation and
  novation. The instrution must include a trade identifier, because a change of party
  effectively results in a different trade.'
display_name: PartyChangeInstruction
document_category: PartyChangeInstruction
weight: 20
fields:
- id: counterparty
  description: The new counterparty who is stepping into the trade. The stepping out
    counterparty is inferred based on the counterparty role that is being updated.
  display_name: PartyChangeInstruction_counterparty
  cardinality: multi
- id: ancillaryParty
  description: Specifies an ancillary party to be added onto the new transaction,
    e.g. the original executing party in an allocation.
  display_name: PartyChangeInstruction_ancillaryParty
- id: partyRole
  description: Specifies an additional party roles to be added on to the new transaction.
  display_name: partyRole
- id: tradeId
  description: The identifier to be assigned to the new trade post change of party.
  display_name: tradeId
  cardinality: multi
