# metamodel_version: 1.11.0id: PerformancePayout
schema_generating: true
description: Contains the necessary specifications for all performance payouts, encompassing
  equity return, dividend, variance, volatility and correlation products.
display_name: PerformancePayout
document_category: PerformancePayout
weight: 20
fields:
- id: payerReceiver
  description: Canonical representation of the payer and receiver parties applicable
    to each payout leg.
  display_name: PayoutBase_payerReceiver
- id: priceQuantity
  description: Each payout leg must implement the quantity concept as a 'resolvable'
    type, which allows for different payout legs to be linked to each other (e.g.
    in the case of cross-curreny products).
  display_name: PayoutBase_priceQuantity
  cardinality: multi
- id: principalPayment
  description: The specification of the principal exchange. Optional as only applicable
    in the case of cross-currency or zero-coupon swaps with a final payment.
  display_name: principalPayment
- id: settlementTerms
  description: Each payout leg must specifies its settlement terms, including the
    delivery type (i.e. cash vs physical, and their respective terms), the transfer
    type (DvP etc.) and settlement date, if any.
  display_name: PayoutBase_settlementTerms
- id: observationTerms
  description: Defines how and when a performance type option or performance type
    swap is to be observed.
  display_name: PerformancePayout_observationTerms
- id: valuationDates
  description: Defines how and when a performance type option or performance type
    swap is to be valued, including both interim and final valuation.
  display_name: PerformancePayout_valuationDates
- id: paymentDates
  description: Defines the payment date schedule, as defined by the parameters that
    are needed to specify it, either in a parametric way or by reference to another
    schedule of dates (e.g. the valuation dates).
  display_name: paymentDates
- id: underlier
  description: Identifies the underlying product that is referenced for pricing of
    the applicable leg in a swap.  Referenced in the '2018 ISDA CDM Equity Confirmation
    for Security Equity Swap' as Security.
  display_name: PerformancePayout_underlier
- id: fxFeature
  description: Defines quanto or composite FX features that are included in the swap
    leg.
  display_name: PerformancePayout_fxFeature
  cardinality: multi
- id: returnTerms
  description: Specifies the type of return of a performance payout.
  display_name: returnTerms
- id: portfolioReturnTerms
  description: Specifies an individual type of return of a Performance Payout, when
    such individual return is part of an aggregation of multiple similar returns,
    at Performance Payout level
  display_name: portfolioReturnTerms
  cardinality: multi
- id: initialValuationPrice
  description: Specifies the net initial valuation price(s) of the underlier at Performance
    Payout level. This price can be expressed either as an actual amount/currency,
    as a determination method, or by reference to another value specified in the swap
    document.
  display_name: PerformancePayout_initialValuationPrice
  cardinality: multi
- id: interimValuationPrice
  description: Specifies the net initial valuation price(s) of the underlier at Performance
    Payout level. This price can be expressed either as an actual amount/currency,
    as a determination method, or by reference to another value specified in the swap
    document.
  display_name: PerformancePayout_interimValuationPrice
  cardinality: multi
- id: finalValuationPrice
  description: Specifies the net final valuation price(s) of the underlier at Performance
    Payout level. This price can be expressed either as an actual amount/currency,
    as a determination method, or by reference to another value specified in the swap
    document.
  display_name: PerformancePayout_finalValuationPrice
  cardinality: multi
