# metamodel_version: 1.11.0id: PositionBase
schema_generating: true
description: Base class to describe a Position, which could be a group of products
  (e.g. trade portfolio) or a group of assets (e.g. collateral portfolio).
display_name: PositionBase
document_category: PositionBase
weight: 20
fields:
- id: priceQuantity
  description: Position with many price quantities.
  display_name: PositionBase_priceQuantity
  cardinality: multi
- id: product
  description: The product underlying the position.
  display_name: PositionBase_product
- id: asset
  description: The asset that underlies the position.
  display_name: asset
- id: cashBalance
  description: The aggregate cost of proceeds.
  display_name: cashBalance
- id: tradeReference
  description: Reference to the Contract, in case product is contractual and the contract
    has been formed.
  display_name: PositionBase_tradeReference
  cardinality: multi
