# metamodel_version: 1.11.0id: QuantityMultiplier
schema_generating: true
description: ' Class to specify a mechanism for a quantity to be set as a multiplier
  to another (reference) quantity, based on a price observation. At the moment this
  class only supports FX or Equity-linked notional and re-uses existing building blocks
  for those 2 cases, until such time when component can be made more generic. This
  captures the case of resetting cross-currency swaps and resetting equity swaps.'
display_name: QuantityMultiplier
document_category: QuantityMultiplier
weight: 20
fields:
- id: fxLinkedNotionalSchedule
  description: Multiplier specified as an FX-linked schedule, e.g. for a resetting
    cross-currency swap..
  display_name: fxLinkedNotionalSchedule
- id: multiplierValue
  display_name: multiplierValue
