# metamodel_version: 1.11.0id: ReferencePair
schema_generating: true
display_name: ReferencePair
document_category: ReferencePair
weight: 20
fields:
- id: referenceEntity
  description: 'The corporate or sovereign entity on which you are buying or selling
    protection and any successor that assumes all or substantially all of its contractual
    and other obligations. It is vital to use the correct legal name of the entity
    and to be careful not to choose a subsidiary if you really want to trade protection
    on a parent company. Please note, Reference Entities cannot be senior or subordinated.
    It is the obligations of the Reference Entities that can be senior or subordinated.
    ISDA 2003 Term: Reference Entity.'
  display_name: ReferencePair_referenceEntity
- id: referenceObligation
  description: 'The Reference Obligation is a financial instrument that is either
    issued or guaranteed by the reference entity. It serves to clarify the precise
    reference entity protection is being offered upon, and its legal position with
    regard to other related firms (parents/subsidiaries). Furthermore the Reference
    Obligation is ALWAYS deliverable and establishes the Pari Passu ranking (as the
    deliverable bonds must rank equal to the reference obligation). ISDA 2003 Term:
    Reference Obligation.'
  display_name: ReferencePair_referenceObligation
  cardinality: multi
- id: noReferenceObligation
  description: Used to indicate that there is no Reference Obligation associated with
    this Credit Default Swap and that there will never be one.
  display_name: noReferenceObligation
- id: entityType
  description: Defines the reference entity types corresponding to a list of types
    in the ISDA First to Default documentation.
  display_name: entityType
