# metamodel_version: 1.11.0id: ResetInstruction
schema_generating: true
description: 'Defines the information needed to create a Reset Business Event. '
display_name: ResetInstruction
document_category: ResetInstruction
weight: 20
fields:
- id: payout
  display_name: payout
  cardinality: multi
- id: rateRecordDate
  description: Specifies the 'Rate Record Day' for a Fallback rate.  Fallback rate
    fixing processes typically set the fixing rate in arrears, i.e., the Fallback
    Rate corresponding to a Rate Record Date is set at the end of the interest accural
    period.  When this applies, Reset->resetDate occurs at the end of the interest
    period, and the Reset->rateRecordDate occurs near the start of the interest period.  The
    Reset->rateRecordDate and Reset->observations->observationIdentifier->observationDate
    will differ if a Fallback rate is unavailable on the Rate Record Date, and the
    latest previous available rate is used as the observation.
  display_name: rateRecordDate
- id: resetDate
  description: Specifies the date on which the reset is occuring.
  display_name: resetDate
