# metamodel_version: 1.11.0id: Restructuring
schema_generating: true
display_name: Restructuring
document_category: Restructuring
weight: 20
fields:
- id: applicable
  description: Indicates whether the restructuring provision is applicable.
  display_name: Restructuring_applicable
- id: restructuringType
  description: Specifies the type of restructuring that is applicable.
  display_name: restructuringType
- id: multipleHolderObligation
  description: 'In relation to a restructuring credit event, unless multiple holder
    obligation is not specified restructurings are limited to multiple holder obligations.
    A multiple holder obligation means an obligation that is held by more than three
    holders that are not affiliates of each other and where at least two thirds of
    the holders must agree to the event that constitutes the restructuring credit
    event. ISDA 2003 Term: Multiple Holder Obligation.'
  display_name: multipleHolderObligation
- id: multipleCreditEventNotices
  description: 'Presence of this element and value set to ''true'' indicates that
    Section 3.9 of the 2003 Credit Derivatives Definitions shall apply. Absence of
    this element indicates that Section 3.9 shall not apply. NOTE: Not allowed under
    ISDA Credit 1999.'
  display_name: multipleCreditEventNotices
