# metamodel_version: 1.11.0id: ReturnTermsBase
schema_generating: true
description: Contains all common elements in variance, volatility and correlation
  return Terms.
display_name: ReturnTermsBase
document_category: ReturnTermsBase
weight: 20
fields:
- id: valuationTerms
  description: Contains all non-date valuation information.
  display_name: valuationTerms
- id: annualizationFactor
  description: This specifies the numerator of an annualization factor. Frequently
    this number is equal to the number of observations of prices in a year e.g. 252.
  display_name: annualizationFactor
- id: dividendApplicability
  description: The parameters which define whether dividends are applicable
  display_name: dividendApplicability
- id: equityUnderlierProvisions
  description: Contains Equity Underlyer provisions regarding jurisdiction and fallbacks.
  display_name: equityUnderlierProvisions
- id: sharePriceDividendAdjustment
  description: Indicates whether the price of shares is adjusted for dividends or
    not.
  display_name: sharePriceDividendAdjustment
- id: expectedN
  description: Expected number of trading days.
  display_name: expectedN
- id: initialLevel
  description: Contract will strike off this initial level. Providing just the initialLevel
    without initialLevelSource, infers that this is AgreedInitialPrice - a specified
    Initial Index Level.
  display_name: initialLevel
- id: initialLevelSource
  description: In this context, this is AgreedInitialPrice - a specified Initial Index
    Level.
  display_name: initialLevelSource
- id: meanAdjustment
  description: Specifies whether Mean Adjustment is applicable or not in the calculation
    of the Realized Volatility, Variance or Correlation
  display_name: meanAdjustment
- id: performance
  description: Performance calculation, in accordance with Part 1 Section 12 of the
    2018 ISDA CDM Equity Confirmation for Security Equity Swap, Para 75. 'Equity Performance'.
    Cumulative performance is used as a notional multiplier factor on both legs of
    an Equity Swap.
  display_name: performance
