# metamodel_version: 1.11.0id: SettlementPayout
schema_generating: true
description: Represents a forward settling payout. The underlier attribute captures
  the underlying payout, which is settled according to the settlementTerms attribute
  (which is part of PayoutBase). Both FX Spot and FX Forward should use this component.
display_name: SettlementPayout
document_category: SettlementPayout
weight: 20
fields:
- id: payerReceiver
  description: Canonical representation of the payer and receiver parties applicable
    to each payout leg.
  display_name: PayoutBase_payerReceiver
- id: priceQuantity
  description: Each payout leg must implement the quantity concept as a 'resolvable'
    type, which allows for different payout legs to be linked to each other (e.g.
    in the case of cross-curreny products).
  display_name: PayoutBase_priceQuantity
  cardinality: multi
- id: principalPayment
  description: The specification of the principal exchange. Optional as only applicable
    in the case of cross-currency or zero-coupon swaps with a final payment.
  display_name: principalPayment
- id: settlementTerms
  description: Each payout leg must specifies its settlement terms, including the
    delivery type (i.e. cash vs physical, and their respective terms), the transfer
    type (DvP etc.) and settlement date, if any.
  display_name: PayoutBase_settlementTerms
- id: underlier
  description: The underlying financial product that will be physically or cash settled,
    which can be of any type, eg an asset such as cash or a security, or the cash
    settlement of an index rate.
  display_name: SettlementPayout_underlier
- id: deliveryTerm
  description: Also called contract month or delivery month. However, it's not always
    a month. It is usually expressed using a code, e.g. Z23 would be the Dec 2023
    contract, (Z = December). For crude oil, the corresponding contract might be called
    CLZ23.
  display_name: SettlementPayout_deliveryTerm
- id: delivery
  description: Contains the information relative to the delivery of the asset.
  display_name: delivery
- id: schedule
  description: Allows the full representation of a payout by defining a set of schedule
    periods. It supports standard schedule customization by expressing all the dates,
    quantities, and pricing data in a non-parametric way.
  display_name: SettlementPayout_schedule
  cardinality: multi
