# metamodel_version: 1.11.0id: SimmException
schema_generating: true
description: A class to specify the SIMM exception to the regulatory regime clause.
display_name: SimmException
document_category: SimmException
weight: 20
fields:
- id: standardisedException
  description: The Standard Initial Margin Model exception when specified by the party
    according to one of the enumerated values.
  display_name: standardisedException
- id: simmExceptionApplicable
  description: The Standard Initial Margin model exception approach applicable when
    specified by the party according to one of the enumerated values.
  display_name: simmExceptionApplicable
- id: asSpecified
  description: The Standard Initial Margin Model exception when specified as a customized
    approach by the party.
  display_name: SimmException_asSpecified
