# metamodel_version: 1.11.0id: SpecifiedEntities
schema_generating: true
description: A provision that allows each party to specify its Specified Entities
  for certain Events of Default and Termination Events.
display_name: SpecifiedEntities
document_category: SpecifiedEntities
weight: 20
fields:
- id: specifiedEntityClause
  description: The Event of Default or Termination event for which Specified Entities
    terms are being defined.
  display_name: specifiedEntityClause
- id: specifiedEntity
  description: The party specific election of Specified Entities for the Event of
    Default or Termination Event specified.
  display_name: specifiedEntity
  cardinality: multi
