# metamodel_version: 1.11.0id: SpecificInconvertibility
schema_generating: true
display_name: SpecificInconvertibility
document_category: SpecificInconvertibility
weight: 20
fields:
- id: specificInconvertibilityIsApplicable
  display_name: specificInconvertibilityIsApplicable
- id: minimumAmount
  display_name: minimumAmount
- id: relevantClass
  display_name: relevantClass
  cardinality: multi
- id: localSubstituteProvisionType
  display_name: localSubstituteProvisionType
- id: maximumDaysOfDisruption
  description: Specifies how long to wait to get a quote from a settlement rate option
    upon a price source disruption.
  display_name: SpecificInconvertibility_maximumDaysOfDisruption
- id: nonDeliverableSubstitute
  display_name: nonDeliverableSubstitute
- id: escrowArrangement
  description: Refers to the segregation deposit procedure parties may want to commmit
    into during the time a Disruption Event is effective
  display_name: SpecificInconvertibility_escrowArrangement
