# metamodel_version: 1.11.0id: State
schema_generating: true
description: Defines the state of a trade at a point in the Trade's life cycle. Trades
  have many state dimensions, all of which are represented here. For example, states
  useful for position keeping are represented alongside those needed for regulatory
  reporting.
display_name: State
document_category: State
weight: 20
fields:
- id: closedState
  description: Represents the qualification of what led to the trade's closure alongside
    the dates on which this closure took effect.
  display_name: closedState
- id: positionState
  description: Identifies the state of the position, to distinguish if just executed,
    formed, already settled, closed, etc.
  display_name: positionState
