# metamodel_version: 1.11.0id: TerminationProvision
schema_generating: true
description: A class for defining option provisions.
display_name: TerminationProvision
document_category: TerminationProvision
weight: 20
fields:
- id: cancelableProvision
  description: A provision that allows the specification of an embedded option within
    a swap giving the buyer of the option the right to terminate the swap, in whole
    or in part, on the early termination date.
  display_name: cancelableProvision
- id: earlyTerminationProvision
  description: Parameters specifying provisions relating to the optional and mandatory
    early termination of a swap transaction.
  display_name: earlyTerminationProvision
- id: evergreenProvision
  description: 'A data defining: the right of a party to exercise an Evergreen option'
  display_name: evergreenProvision
- id: extendibleProvision
  description: A provision that allows the specification of an embedded option with
    a swap giving the buyer of the option the right to extend the swap, in whole or
    in part, to the extended termination date.
  display_name: extendibleProvision
- id: recallProvision
  description: A provision defining criteria controlling the ability for a lender
    to recall securities it has lent out.
  display_name: recallProvision
