# metamodel_version: 1.11.0id: Trade
schema_generating: true
description: Defines the output of a financial transaction between parties - a Business
  Event. A Trade impacts the financial position (i.e. the balance sheet) of involved
  parties.
display_name: Trade
document_category: Trade
weight: 20
fields:
- id: product
  description: The underlying product to be included in a contract or execution.
  display_name: TradableProduct_product
- id: tradeLot
  description: Specifies the price, quantity and effective date of each trade lot,
    when the same product may be traded multiple times in different lots with the
    same counterparty. In a trade increase, a new trade lot is added to the list,
    with the corresponding effective date. In a trade decrease, the existing trade
    lot(s) are decreased of the corresponding quantity (and an unwind fee may have
    to be settled). The multiple cardinality and the ability to increase existing
    trades is used for Equity Swaps in particular.
  display_name: tradeLot
  cardinality: multi
- id: counterparty
  description: Specifies the parties which are the two counterparties to the transaction.  The
    product is agnostic to the actual parties to the transaction, with the party references
    abstracted away from the product definition and replaced by the counterparty enum
    (e.g. CounterpartyEnum values Party1 or Party2). The counterparty enum can then
    be positioned in the product (e.g. to specify which counterparty is the payer,
    receiver etc) and this counterparties attribute, which is positioned outside of
    the product definition, allows the counterparty enum to be associated with an
    actual party reference.
  display_name: TradableProduct_counterparty
  cardinality: multi
- id: ancillaryParty
  description: Specifies the parties with ancillary roles in the transaction. The
    product is agnostic to the actual parties involved in the transaction, with the
    party references abstracted away from the product definition and replaced by the
    AncillaryRoleEnum. The AncillaryRoleEnum can then be positioned in the product
    and this AncillaryParty type, which is positioned outside of the product definition,
    allows the AncillaryRoleEnum to be associated with an actual party reference.
  display_name: TradableProduct_ancillaryParty
  cardinality: multi
- id: adjustment
  description: 'Specifies the conditions that govern the adjustment to the quantity
    of a product being traded: e.g. execution, portfolio rebalancing etc. It is typically
    used in the context of Equity Swaps.'
  display_name: TradableProduct_adjustment
- id: tradeIdentifier
  description: Represents the identifier(s) that uniquely identify a trade for an
    identity issuer. A trade can include multiple identifiers, for example a trade
    that is reportable to both the CFTC and ESMA, and then has an associated USI (Unique
    Swap Identifier) UTI (Unique Trade Identifier).
  display_name: Trade_tradeIdentifier
  cardinality: multi
- id: tradeDate
  description: Specifies the date which the trade was agreed.
  display_name: Trade_tradeDate
- id: tradeTime
  description: Denotes the trade time and timezone as agreed by the parties to the
    trade.
  display_name: tradeTime
- id: party
  description: Represents the parties to the trade. The cardinality is optional to
    address the case where the trade is defined within a BusinessEvent data type,
    in which case the party is specified in BusinessEvent.
  display_name: Trade_party
  cardinality: multi
- id: partyRole
  description: Represents the role each specified party takes in the trade. further
    to the principal roles, payer and receiver.
  display_name: Trade_partyRole
  cardinality: multi
- id: executionDetails
  description: Represents information specific to trades that arose from executions.
  display_name: Trade_executionDetails
- id: contractDetails
  description: Represents information specific to trades involving contractual products.
  display_name: contractDetails
- id: clearedDate
  description: Specifies the date on which a trade is cleared (novated) through a
    central counterparty clearing service.
  display_name: clearedDate
- id: collateral
  description: Represents the collateral obligations of a party.
  display_name: Trade_collateral
- id: account
  description: Represents a party's granular account information, which may be used
    in subsequent internal processing.
  display_name: Trade_account
  cardinality: multi
