# metamodel_version: 1.11.0id: TransferContactInformation
schema_generating: true
description: Specifies transfer information including address and, optionally, an
  associated account. This type also supports the ISDA CSA representation as a single
  string, through the address attribute in Contact Information.
display_name: TransferContactInformation
document_category: TransferContactInformation
weight: 20
fields:
- id: telephone
  description: The telephone number.
  display_name: telephone
  cardinality: multi
- id: address
  description: The street/postal address.
  display_name: address
  cardinality: multi
- id: email
  description: The email address.
  display_name: email
  cardinality: multi
- id: webPage
  description: The web page. This attribute is not specified as part of the FpML ContactInformation
    complex type.
  display_name: webPage
  cardinality: multi
- id: account
  description: Specifies the account infomation for transfers to a party.
  display_name: TransferContactInformation_account
  cardinality: multi
- id: additionalInformation
  description: Additional transfer information.
  display_name: TransferContactInformation_additionalInformation
