# metamodel_version: 1.11.0id: ValuationTerms
schema_generating: true
display_name: ValuationTerms
document_category: ValuationTerms
weight: 20
fields:
- id: futuresPriceValuation
  description: The official settlement price as announced by the related exchange
    is applicable, in accordance with the ISDA 2002 definitions.
  display_name: futuresPriceValuation
- id: optionsPriceValuation
  description: The official settlement price as announced by the related exchange
    is applicable, in accordance with the ISDA 2002 definitions
  display_name: optionsPriceValuation
- id: numberOfValuationDates
  description: The number of valuation dates between valuation start date and valuation
    end date.
  display_name: numberOfValuationDates
- id: dividendValuationDates
  description: Specifies the dividend valuation dates of the swap.
  display_name: dividendValuationDates
- id: fPVFinalPriceElectionFallback
  description: Specifies the fallback provisions for Hedging Party in the determination
    of the Final Price.
  display_name: fPVFinalPriceElectionFallback
- id: multipleExchangeIndexAnnexFallback
  description: For an index option transaction, a flag to indicate whether a relevant
    Multiple Exchange Index Annex is applicable to the transaction. This annex defines
    additional provisions which are applicable where an index is comprised of component
    securities that are traded on multiple exchanges.
  display_name: multipleExchangeIndexAnnexFallback
- id: componentSecurityIndexAnnexFallback
  description: For an index option transaction, a flag to indicate whether a relevant
    Component Security Index Annex is applicable to the transaction.
  display_name: componentSecurityIndexAnnexFallback
